gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"

gText_Pie_Welcome::
	.string "Oh, wait!\p"
	.string "Before you go, a message from this\n"
	.string "hack's creator:\p"
	.string "Welcome to Pokémon Inclement Emerald!\p"
	.string "This is a difficulty hack with modern\n"
	.string "mechanics, many quality of life\l"
	.string "changes, and massive Pokémon variety!\p"
	.string "You can build your team using almost\n"
	.string "any Pokémon from the first seven\l"
	.string "generations, and gen eight will be\l"
	.string "added soon too!\p"
	.string "Before you get started, you'll need\n"
	.string "to choose a difficulty setting.\p"
	.string "Currently you can choose between\n"
	.string "Normal, Hard or Challenge Mode.\p"
	.string "Please select a mode to learn more\n"
	.string "about it.$"

gText_Pie_NormalMode::
	.string "In Normal Mode, Trainers won't have\n"
	.string "EVs, so you won't need to worry\l"
	.string "about your own Pokémon's stats.\p"
	.string "This difficulty is recommended if\n"
	.string "you're new to difficulty hacks, or\l"
	.string "if you don't want to deal with EVs.\p"
	.string "So, would you like to play on\n"
	.string "Normal Mode?$"

gText_Pie_HardMode::
	.string "In Hard Mode, Trainers will have EV-\n"
	.string "trained Pokémon, so you might\l"
	.string "want to EV train your own team.\p"
	.string "You can do this passively - no\n"
	.string "grinding required - so don't let that\l"
	.string "put you off!\p"
	.string "This difficulty is recommended for\n"
	.string "experienced players.\p"
	.string "So, would you like to play on\n"
	.string "Hard Mode?$"

gText_Pie_ChallengeMode::
	.string "Like Hard Mode, Trainers in Challenge\n"
	.string "Mode have EV trained teams.\p"
	.string "It also adds two restrictions:\p"
	.string "You can't access the bag in Trainer\n"
	.string "Battles, and the Shift battle style is\l"
	.string "disabled.\p"
	.string "That means you'll follow the same rules\n"
	.string "as your opponents, so good strategy\l"
	.string "and a balanced team are more important\l"
	.string "in this mode.\p"
	.string "This difficulty is only recommended if\n"
	.string "it sounds appealing to you!\p"
	.string "So, would you like to play on\n"
	.string "Challenge Mode?$"

gText_Pie_WhichDifficulty::
	.string "Which difficulty would you like to\n"
	.string "play on?$"

gText_Pie_LevelCaps::
    .string "Great! Now, there's one last thing\n"
    .string "to decide.\p"
    .string "This hack has built-in level caps\n"
    .string "based on which badges you have.\p"
    .string "If a Pokémon reaches the level cap,\n"
    .string "it'll only get 1 exp per KO until\l"
	.string "you earn the next badge.\p"
    .string "There are currently three different\n"
	.string "settings for level caps.\p"
    .string "Please choose a level cap setting to\n"
    .string "learn more about it.$"

gText_Pie_StandardCaps::
	.string "The Default Caps setting is what\n"
	.string "the game is designed around.\p"
	.string "With this option, level caps are only\n"
	.string "present for the first four badges.\p"
	.string "After that, there is no cap, and you\n"
	.string "can train all the way to level 100.\p"
	.string "So, would you like to play with\n"
	.string "default level caps?$"

gText_Pie_MoreCaps::
	.string "The More Caps setting simply adds\n"
	.string "more level caps to the game.\p"
	.string "With this option, there will be a\n"
	.string "level cap tied to each badge, and you\l"
	.string "won't be able to reach level 100\l"
	.string "before becoming Champion.\p"
	.string "So, would you like to play with\n"
	.string "more level caps?$"

gText_Pie_StrictCaps::
	.string "The Strict Caps setting throws game\n"
	.string "balance out the window and gives you\l"
	.string "much lower level caps.\p"
	.string "With this option, there will be a\n"
	.string "level cap tied to each badge, and you\l"
	.string "won't be able to reach level 100\l"
	.string "before becoming Champion.\p"
	.string "However, the caps are not designed\n"
	.string "around the hack's steep level curve,\l"
	.string "which limits your options for the\l"
	.string "first half of the game.\p"
	.string "Also, your opponents will still use\n"
	.string "teams designed for the default caps,\l"
	.string "so please be sure you're OK with that\l"
	.string "before choosing this setting!\p"
	.string "So, would you like to play with\n"
	.string "strict level caps?$"

gText_Pie_WhichLevelCapSetting::
	.string "Which level cap setting would you\n"
	.string "like play on?$"

gText_Pie_Documents::
	.string "Great! If you want more information,\n"
	.string "please check the documents that came\l"
	.string "with the hack's patch.\p"
	.string "They cover everything from Pokémon and\n"
	.string "item locations to new ability effects.\p"
	.string "Finally, I hope you enjoy the hack!\n"
	.string "- Buffel Saft\p"
	.string "$"
