MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce: @ 82C6E05
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_MimicTeach: @ 82C72B6
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move MIMIC?$"

MoveTutor_MimicDeclined: @ 82C737F
	.string "Oh, boo! I wanted to teach Mimic\n"
	.string "to your Pokémon!$"

MoveTutor_Text_MimicWhichMon: @ 82C73B1
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the Pokémon\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught: @ 82C73F6
	.string "Mimic is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_MetronomeTeach: @ 82C7449
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your Pokémon\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your Pokémon\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined: @ 82C7556
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon: @ 82C7582
	.string "Okay! I'll teach it!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_MetronomeTaught: @ 82C75B5
	.string "When a Pokémon waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_DynamicPunchTeach: @ 82C79A6
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type Trainer,\n"
	.string "so I can't win at the Mossdeep Gym\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "Pokémon DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined: @ 82C7AD4
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon: @ 82C7B0D
	.string "What? You do? You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_DynamicPunchTaught: @ 82C7B4F
	.string "I want you to win at the Mossdeep Gym\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach: @ 82C7B8E
	.string "Sigh…\p"
	.string "Sootopolis's Gym Leader is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your Pokémon\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined: @ 82C7C7E
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon: @ 82C7C98
	.string "Okay, which Pokémon should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught: @ 82C7CC8
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"
