gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "Hello, and welcome to\n"
    .string "the Pokémon Center.\p"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn:: @ 8272768
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Thank you for waiting.\p"
    .string "We've restored your Pokémon\n"
    .string "to full health.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "We hope to see you again!$"

gText_WelcomeCutShort:: @ 82727F5
    .string "Hello, and welcome to\n"
    .string "the Pokémon Center.\p"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "Would you like to…$"

gText_NoticesGoldCard:: @ 8272860
    .string "Th-that card…\n"
    .string "Could it be… The Gold Card?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several Trainers with\n"
    .string "a Silver Card before, but, {PLAYER},\l"
    .string "you're the first Trainer I've ever\l"
    .string "seen with a Gold Card!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your Pokémon!$"

gText_YouWantTheUsual:: @ 8272982
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2:: @ 82729C0
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "We hope to see you again!$"

gText_AreYouARookieTrainer:: 
    .string "Hello, and welcome to\n"
    .string "the Pokémon Center.\p"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "This is your first time here,\n"
    .string "isn't it?\p"
    .string "It's your lucky day!\p"
    .string "We're currently giving out free\n"
    .string "Poké Vials to all rookie Trainers.\p"
    .string "Here, take one!$"

gText_ExplainPokeVial:: 
    .string "That Poké Vial contains very potent\n"
    .string "medicine.\p"
    .string "It's strong enough to heal your entire\n"
    .string "party, but you can't use it in battles,\l"
    .string "and there's only enough to use it once.\p"
    .string "But here's the good part: every time\n"
    .string "you heal up at a Pokémon Center, we'll\l"
    .string "refill it for free.\p"
    .string "It's like a portable Pokémon Center!\p"
    .string "Now, would you like to rest your\n"
    .string "Pokémon?$"
