name: build
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Packages on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y python3
      - uses: actions/checkout@v2
      - name: Build PokeEmerald ROM
        run: |
          ./build.sh