name: build
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ubuntu Build Deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y python3 make build-essential wget curl git
      - uses: actions/checkout@v2
      - name: Install DevkitARM
        run: |
          wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb -O /tmp/dkp_pacman.deb
          sudo apt install -y /tmp/dkp_pacman.deb
          sudo dkp-pacman -Sy
          sudo dkp-pacman -S --noconfirm gba-dev
      - name: Build PokeEmerald ROM
        run: |
          source /etc/profile.d/devkit-env.sh
          ./build.sh
      - name: Check PokeEmerald ROM
        run: true