name: build
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ubuntu Build Deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y python3 make build-essential wget curl git podman
      - uses: actions/checkout@v2
      - name: Build PokeEmerald ROM
        run: |
          podman run --rm -it -v $(pwd):/source docker.io/xdrie/dkarm_base:v0.6 -l -c 'apt install -y libpng-dev && ./build.sh && make -j$(nproc)'
      - name: Check PokeEmerald ROM
        run: true